#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
COPY ["PowerplantCodingChallenge.csproj", "PowerplantCodingChallenge/"]
RUN dotnet restore "PowerplantCodingChallenge/PowerplantCodingChallenge.csproj"
COPY . PowerplantCodingChallenge/

FROM build AS publish
RUN dotnet publish "PowerplantCodingChallenge/PowerplantCodingChallenge.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PowerplantCodingChallenge.dll"]